// src/lib/lead-qualification-client.ts
//
// Client helper for the Leads page's "Run Lead Qualification" action and
// the AI Center settings toggle — same shape as gmail-sync-client.ts
// (shared auth-session helper, typed result, no direct Supabase writes for
// anything this sensitive). Never uses Test Console fixture data — always
// the real, authenticated caller's org and a real leadId.

import { resolveAuthSession } from "@/lib/auth-session";

export type RunLeadQualificationResult =
  | { status: "recommendation"; claimId: string; executionId: string; responseText?: string }
  | { status: "awaiting_approval"; claimId: string; executionId: string; approvalRequestId: string }
  | { status: "skipped"; reason: string; message?: string }
  | { status: "error"; error: string };

/**
 * `invocationId`: ONE id per intentional click, generated by the caller
 * (see leads.tsx's handleRunLeadQualification) and reused unchanged for any
 * retry of that exact click — never regenerated per call. A later, separate
 * click must pass a NEW id. The server only validates its shape; identity/
 * authorization always come from the bearer token.
 */
export async function runLeadQualification(leadId: string, invocationId: string): Promise<RunLeadQualificationResult> {
  const session = await resolveAuthSession();
  if (!session) return { status: "error", error: "You must be signed in." };
  try {
    const res = await fetch("/.netlify/functions/lead-qualification-trigger", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` },
      body: JSON.stringify({ leadId, invocationId }),
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) return { status: "error", error: json.error ?? "Lead Qualification run failed." };
    return json as RunLeadQualificationResult;
  } catch {
    return { status: "error", error: "Network error — Lead Qualification did not run." };
  }
}

export type LeadQualificationSettings = { enabled: boolean; defaultAutonomyLevel: 1 | 2 };

export async function fetchLeadQualificationSettings(): Promise<LeadQualificationSettings | null> {
  const session = await resolveAuthSession();
  if (!session) return null;
  try {
    const res = await fetch("/.netlify/functions/lead-qualification-settings", {
      headers: { Authorization: `Bearer ${session.access_token}` },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function saveLeadQualificationSettings(settings: LeadQualificationSettings): Promise<{ ok: boolean; error?: string }> {
  const session = await resolveAuthSession();
  if (!session) return { ok: false, error: "You must be signed in." };
  try {
    const res = await fetch("/.netlify/functions/lead-qualification-settings", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` },
      body: JSON.stringify(settings),
    });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) return { ok: false, error: json.error ?? "Could not save settings." };
    return { ok: true };
  } catch {
    return { ok: false, error: "Network error — settings not saved." };
  }
}
