-- Phase 10.4 — Estimates, Proposals, Approvals, and Payments Completion.
--
-- Extends the existing, already-live public.estimates / public.estimate_items
-- tables in place (confirmed via a live schema check first — estimates
-- already has: id, org_id, created_by, client_id (NOT NULL -> contacts.id),
-- title, status, subtotal/tax_total/discount_total/total, currency, notes,
-- terms, pdf_url, signed_at, number, valid_until, sent_at, viewed_at,
-- client_name, deal_id, project_id, cost_total, contingency,
-- contractor_margin, client_total, esign_status). Reused directly rather
-- than duplicated. Adds only what's genuinely missing: the customer/company/
-- lead/owner relationships, deposit/discount/tax fields, lifecycle
-- timestamps, secure public-proposal token + view tracking, a lightweight
-- version-snapshot table, and a real activity table — mirroring the exact
-- patterns already established for appointments (20260807) and projects
-- (20260808): guarded DDL, same-org validation triggers, org-scoped RLS,
-- one trigger-owned activity log.
--
-- Additive only. Does not modify any prior migration. Every statement is
-- guarded so re-running this file against a database where it already
-- applied cleanly is a no-op. Not run automatically — see the deployment
-- instructions in the accompanying report.

begin;

-- ── estimates: new columns ───────────────────────────────────────────────
alter table public.estimates
  add column if not exists company_id uuid null,
  add column if not exists lead_id uuid null,
  add column if not exists owner_id uuid null,
  add column if not exists version_number integer not null default 1,
  add column if not exists discount_type text null,
  add column if not exists discount_value numeric null default 0,
  add column if not exists tax_rate numeric not null default 0,
  add column if not exists deposit_type text null,
  add column if not exists deposit_value numeric null default 0,
  add column if not exists deposit_amount numeric not null default 0,
  add column if not exists balance_due numeric not null default 0,
  add column if not exists scope text null,
  add column if not exists exclusions text null,
  add column if not exists assumptions text null,
  add column if not exists customer_note text null,
  add column if not exists public_token text null,
  add column if not exists first_viewed_at timestamptz null,
  add column if not exists last_viewed_at timestamptz null,
  add column if not exists view_count integer not null default 0,
  add column if not exists approved_at timestamptz null,
  add column if not exists rejected_at timestamptz null,
  add column if not exists changes_requested_at timestamptz null,
  add column if not exists expired_at timestamptz null,
  add column if not exists converted_at timestamptz null,
  add column if not exists cancelled_at timestamptz null,
  add column if not exists converted_deal_id uuid null,
  add column if not exists converted_project_id uuid null,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

comment on column public.estimates.number is
  'Organization-scoped human-readable number (EST-000001). Generated by set_estimate_number() below on INSERT — never computed client-side (a prior client-side "count + 1"/random-suffix generator is replaced, not just supplemented). Immutable after creation.';
comment on column public.estimates.public_token is
  'High-entropy token (32 random bytes, hex) for the anonymous customer proposal route. Never derived from estimate.id. Null until first sent. Looked up only through netlify/functions/proposal-data.ts (service-role), never a client-side/anon table grant.';
comment on column public.estimates.version_number is
  'Increments when a sent/viewed estimate''s customer-visible fields are revised (see estimate_versions for the immutable snapshot of what version_number pointed to before the change).';
comment on column public.estimates.deposit_amount is
  'Snapshotted numeric deposit due, resolved server-side from deposit_type/deposit_value at save time — never trusted from a client-supplied exact figure alone at approval time.';

-- ── backfill ──────────────────────────────────────────────────────────────
-- Normalizes the one pre-existing status synonym ("declined") to the
-- canonical "rejected" value before the widened check constraint below is
-- added, so no live row is ever rejected by its own migration.
update public.estimates set status = 'rejected' where status = 'declined';

-- ── status check: canonical lifecycle ────────────────────────────────────
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'estimates_status_check' and conrelid = 'public.estimates'::regclass
  ) then
    alter table public.estimates drop constraint estimates_status_check;
  end if;

  alter table public.estimates
    add constraint estimates_status_check
    check (status in (
      'draft', 'ready', 'sent', 'viewed', 'changes_requested', 'approved',
      'rejected', 'expired', 'converted', 'cancelled', 'archived'
    ));
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'estimates_discount_type_check' and conrelid = 'public.estimates'::regclass
  ) then
    alter table public.estimates
      add constraint estimates_discount_type_check
      check (discount_type is null or discount_type in ('percent', 'fixed'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'estimates_deposit_type_check' and conrelid = 'public.estimates'::regclass
  ) then
    alter table public.estimates
      add constraint estimates_deposit_type_check
      check (deposit_type is null or deposit_type in ('percent', 'fixed'));
  end if;
end $$;

-- ── foreign keys ──────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'estimates_company_id_fkey' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_company_id_fkey foreign key (company_id) references public.companies(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'estimates_lead_id_fkey' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_lead_id_fkey foreign key (lead_id) references public.leads(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'estimates_owner_id_fkey' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_owner_id_fkey foreign key (owner_id) references public.profiles(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'estimates_converted_deal_id_fkey' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'estimates_converted_project_id_fkey' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_converted_project_id_fkey foreign key (converted_project_id) references public.projects(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'estimates_public_token_key' and conrelid = 'public.estimates'::regclass) then
    alter table public.estimates add constraint estimates_public_token_key unique (public_token);
  end if;
end $$;

-- ── same-org validation triggers (mirror validate_project_owner/_lead) ───
create or replace function public.validate_estimate_relationships()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.org_id is null then
    raise exception 'estimates.org_id is required';
  end if;

  if new.owner_id is not null and not exists (
    select 1 from public.org_memberships where member_id = new.owner_id and org_id = new.org_id
    union
    select 1 from public.profiles where id = new.owner_id and organization_id = new.org_id
  ) then
    raise exception 'Estimate owner is not a member of this organization';
  end if;

  if new.company_id is not null and not exists (
    select 1 from public.companies where id = new.company_id and org_id = new.org_id
  ) then
    raise exception 'Linked account not found in this organization';
  end if;

  if new.lead_id is not null and not exists (
    select 1 from public.leads where id = new.lead_id and org_id = new.org_id
  ) then
    raise exception 'Linked lead not found in this organization';
  end if;

  return new;
end;
$$;

comment on function public.validate_estimate_relationships() is
  'Enforces that estimates.owner_id/company_id/lead_id all belong to estimates.org_id. SECURITY INVOKER: relies on the acting user''s own RLS-scoped read access (client_id/deal_id/project_id already have real FKs with their own referential integrity).';

drop trigger if exists estimates_validate_relationships on public.estimates;
create trigger estimates_validate_relationships
  before insert or update of owner_id, company_id, lead_id, org_id on public.estimates
  for each row
  execute function public.validate_estimate_relationships();

-- ── organization-scoped estimate numbering (never client-side count+1) ───
create sequence if not exists public.estimate_number_seq;

create or replace function public.set_estimate_number()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_next bigint;
begin
  if new.number is not null then
    return new;
  end if;

  -- Per-organization sequential counter derived transactionally from the
  -- org's own current max — guarded with an advisory lock on org_id so two
  -- concurrent inserts for the same org can never compute the same next
  -- number (a bare "select max(...)+1" alone is not concurrency-safe).
  perform pg_advisory_xact_lock(hashtext('estimate_number:' || new.org_id::text));

  select coalesce(max(substring(number from 'EST-(\d+)')::bigint), 0) + 1
    into v_next
    from public.estimates
    where org_id = new.org_id and number ~ '^EST-\d+$';

  new.number := 'EST-' || lpad(v_next::text, 6, '0');
  return new;
end;
$$;

comment on function public.set_estimate_number() is
  'Phase 10.4 — assigns estimates.number (EST-000001 format) server-side on INSERT when not already set. Org-scoped, advisory-lock-guarded for concurrency safety. Immutable thereafter (no UPDATE trigger).';

drop trigger if exists estimates_set_number on public.estimates;
create trigger estimates_set_number
  before insert on public.estimates
  for each row
  execute function public.set_estimate_number();

-- ── estimate_items: relax category, add canonical item fields ───────────
-- category becomes free text (section headings like "Demolition"/"Framing"
-- don't fit the old 6-value enum) while item_type carries the new
-- canonical labor/material/service/... vocabulary. Existing category
-- values (Labor/Materials/Equipment/Permits/Subcontractor/Other) remain
-- valid strings — nothing is rewritten.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'estimate_items_category_check' and conrelid = 'public.estimate_items'::regclass
  ) then
    alter table public.estimate_items drop constraint estimate_items_category_check;
  end if;
end $$;

alter table public.estimate_items
  add column if not exists item_type text null,
  add column if not exists taxable boolean not null default true,
  add column if not exists optional boolean not null default false,
  add column if not exists selected_by_customer boolean not null default true,
  add column if not exists is_heading boolean not null default false,
  add column if not exists discount_type text null,
  add column if not exists discount_value numeric null default 0,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

comment on column public.estimate_items.is_heading is
  'True for a section heading row (e.g. "Demolition") — display-only, never contributes to totals. category holds the heading label in that case.';
comment on column public.estimate_items.selected_by_customer is
  'For optional=true rows: whether the customer included this item when approving. Always true for non-optional rows. Frozen at approval time — never editable after the estimate reaches approved/rejected/converted.';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'estimate_items_item_type_check' and conrelid = 'public.estimate_items'::regclass
  ) then
    alter table public.estimate_items
      add constraint estimate_items_item_type_check
      check (item_type is null or item_type in (
        'labor', 'material', 'service', 'equipment', 'allowance', 'fee', 'discount', 'custom'
      ));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'estimate_items_discount_type_check' and conrelid = 'public.estimate_items'::regclass
  ) then
    alter table public.estimate_items
      add constraint estimate_items_discount_type_check
      check (discount_type is null or discount_type in ('percent', 'fixed'));
  end if;
end $$;

-- ── estimate_versions — immutable snapshot taken whenever a sent/viewed
-- estimate is revised (Part 8). Stores the full prior state as JSONB
-- rather than duplicating every relational row, per "use the cleanest
-- existing model" — there is no pre-existing version table to reuse.
create table if not exists public.estimate_versions (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  estimate_id uuid not null references public.estimates(id) on delete cascade,
  version_number integer not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid null references public.profiles(id) on delete set null
);

comment on table public.estimate_versions is
  'Phase 10.4 — immutable snapshot of an estimate''s customer-visible state (title, scope, terms, items, totals) at the moment a new revision superseded it. snapshot is a point-in-time JSONB copy, not a live relationship — it must never be joined against current estimate_items.';

create unique index if not exists uq_estimate_versions_estimate_version on public.estimate_versions (estimate_id, version_number);

alter table public.estimate_versions enable row level security;

drop policy if exists estimate_versions_org_scoped_select on public.estimate_versions;
create policy estimate_versions_org_scoped_select on public.estimate_versions
  for select
  using (
    org_id in (
      select org_id from public.org_memberships where member_id = auth.uid()
      union
      select organization_id from public.profiles where id = auth.uid()
    )
  );

drop policy if exists estimate_versions_org_scoped_insert on public.estimate_versions;
create policy estimate_versions_org_scoped_insert on public.estimate_versions
  for insert
  with check (
    org_id in (
      select org_id from public.org_memberships where member_id = auth.uid()
      union
      select organization_id from public.profiles where id = auth.uid()
    )
  );

-- ── estimate_activities — real activity history (Part 25) ───────────────
create table if not exists public.estimate_activities (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  estimate_id uuid not null references public.estimates(id) on delete cascade,
  version_number integer null,
  activity_type text not null,
  actor_id uuid null,
  actor_type text not null default 'user',
  title text not null,
  description text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.estimate_activities is
  'Phase 10.4 — estimate lifecycle history. Core status-change events are written by log_estimate_activity() (trigger, below); send/view/response events specific to the public proposal flow are written by the service-role Netlify functions (proposal-data.ts/proposal-action.ts/estimate-send.ts), which have no authenticated session for the trigger''s auth.uid() to resolve — both paths are additive, never duplicating the same event.';
comment on column public.estimate_activities.actor_type is
  '"user" (real auth.uid()), "customer" (public proposal action), or "system" (service-role/automated, e.g. expiration). actor_id is null for both customer and system.';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'estimate_activities_type_check' and conrelid = 'public.estimate_activities'::regclass
  ) then
    alter table public.estimate_activities
      add constraint estimate_activities_type_check
      check (activity_type in (
        'created', 'updated', 'marked_ready', 'sent', 'viewed', 'changes_requested',
        'revision_created', 'approved', 'rejected', 'expired', 'cancelled', 'restored',
        'converted_to_deal', 'converted_to_project', 'invoice_created', 'deposit_requested',
        'payment_received', 'duplicated', 'archived'
      ));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'estimate_activities_actor_type_check' and conrelid = 'public.estimate_activities'::regclass
  ) then
    alter table public.estimate_activities
      add constraint estimate_activities_actor_type_check
      check (actor_type in ('user', 'customer', 'system'));
  end if;
end $$;

create index if not exists idx_estimate_activities_estimate_created on public.estimate_activities (estimate_id, created_at desc);
create index if not exists idx_estimate_activities_org_created on public.estimate_activities (org_id, created_at desc);

alter table public.estimate_activities enable row level security;

drop policy if exists estimate_activities_org_scoped_select on public.estimate_activities;
create policy estimate_activities_org_scoped_select on public.estimate_activities
  for select
  using (
    org_id in (
      select org_id from public.org_memberships where member_id = auth.uid()
      union
      select organization_id from public.profiles where id = auth.uid()
    )
  );

-- No authenticated INSERT/UPDATE/DELETE policy — rows are written only by
-- log_estimate_activity() (SECURITY DEFINER, below) or service-role
-- Netlify functions, both of which bypass RLS by design.

create or replace function public.log_estimate_activity()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid;
begin
  v_actor := auth.uid();

  if tg_op = 'INSERT' then
    insert into public.estimate_activities (org_id, estimate_id, version_number, activity_type, actor_id, actor_type, title)
    values (new.org_id, new.id, new.version_number, 'created', v_actor, case when v_actor is null then 'system' else 'user' end, 'Estimate created');
    return new;
  end if;

  if old.status is distinct from new.status then
    case new.status
      when 'ready' then
        insert into public.estimate_activities (org_id, estimate_id, version_number, activity_type, actor_id, actor_type, title)
        values (new.org_id, new.id, new.version_number, 'marked_ready', v_actor, case when v_actor is null then 'system' else 'user' end, 'Marked ready');
      when 'cancelled' then
        insert into public.estimate_activities (org_id, estimate_id, version_number, activity_type, actor_id, actor_type, title)
        values (new.org_id, new.id, new.version_number, 'cancelled', v_actor, case when v_actor is null then 'system' else 'user' end, 'Estimate cancelled');
      when 'archived' then
        insert into public.estimate_activities (org_id, estimate_id, version_number, activity_type, actor_id, actor_type, title)
        values (new.org_id, new.id, new.version_number, 'archived', v_actor, case when v_actor is null then 'system' else 'user' end, 'Estimate archived');
      when 'draft' then
        if old.status in ('cancelled', 'rejected', 'expired') then
          insert into public.estimate_activities (org_id, estimate_id, version_number, activity_type, actor_id, actor_type, title)
          values (new.org_id, new.id, new.version_number, 'restored', v_actor, case when v_actor is null then 'system' else 'user' end, 'Estimate restored to draft');
        end if;
      else null; -- sent/viewed/approved/rejected/changes_requested/expired/converted are written explicitly by the app-layer/proposal functions that own those transitions (they carry customer-facing context a generic trigger can't produce honestly)
    end case;
  end if;

  return new;
end;
$$;

revoke all on function public.log_estimate_activity() from public;

comment on function public.log_estimate_activity() is
  'Phase 10.4 — AFTER INSERT/UPDATE ON estimates. Owns only the internal-user-driven transitions (created/marked_ready/cancelled/archived/restored); sent/viewed/approved/rejected/changes_requested/expired/converted are written explicitly by their owning code path (estimate-send.ts, proposal-action.ts, the conversion actions) since those need customer-facing context this generic trigger cannot honestly produce.';

drop trigger if exists estimates_log_activity on public.estimates;
create trigger estimates_log_activity
  after insert or update on public.estimates
  for each row
  execute function public.log_estimate_activity();

-- ── invoices: link back to the originating estimate (Part 31) ───────────
alter table public.invoices
  add column if not exists estimate_id uuid null,
  add column if not exists is_deposit boolean not null default false;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'invoices_estimate_id_fkey' and conrelid = 'public.invoices'::regclass) then
    alter table public.invoices add constraint invoices_estimate_id_fkey foreign key (estimate_id) references public.estimates(id) on delete set null;
  end if;
end $$;

-- ── indexes ───────────────────────────────────────────────────────────────
create index if not exists idx_estimates_org_created on public.estimates (org_id, created_at desc);
create index if not exists idx_estimates_org_status on public.estimates (org_id, status);
create index if not exists idx_estimates_contact on public.estimates (client_id);
create index if not exists idx_estimates_company on public.estimates (company_id) where company_id is not null;
create index if not exists idx_estimates_lead on public.estimates (lead_id) where lead_id is not null;
create index if not exists idx_estimates_deal on public.estimates (deal_id) where deal_id is not null;
create index if not exists idx_estimates_project on public.estimates (project_id) where project_id is not null;
create index if not exists idx_estimates_owner on public.estimates (owner_id) where owner_id is not null;
create index if not exists idx_estimates_valid_until on public.estimates (valid_until) where valid_until is not null;
create index if not exists idx_estimate_items_estimate_position on public.estimate_items (estimate_id, position);
create index if not exists idx_invoices_estimate on public.invoices (estimate_id) where estimate_id is not null;

commit;
