/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as SettingsPipelinesRouteImport } from './routes/settings.pipelines'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsFavoritesRouteImport } from './routes/settings.favorites'
import { Route as SettingsCustomFieldsRouteImport } from './routes/settings.custom-fields'
import { Route as SettingsBrandingRouteImport } from './routes/settings.branding'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SalesPipelineRouteImport } from './routes/sales.pipeline'
import { Route as ProjectsClientSlugRouteImport } from './routes/projects.$clientSlug'
import { Route as InsightsReputationRouteImport } from './routes/insights.reputation'
import { Route as InsightsAnalyticsRouteImport } from './routes/insights.analytics'
import { Route as InboxTemplatesRouteImport } from './routes/inbox.templates'
import { Route as InboxBroadcastsRouteImport } from './routes/inbox.broadcasts'
import { Route as FinancialsReportsRouteImport } from './routes/financials.reports'
import { Route as FinancialsPaymentsRouteImport } from './routes/financials.payments'
import { Route as FinancialsInvoicesRouteImport } from './routes/financials.invoices'
import { Route as FinancialsEstimatesRouteImport } from './routes/financials.estimates'
import { Route as AutomationWorkflowsRouteImport } from './routes/automation.workflows'
import { Route as AutomationTriggersRouteImport } from './routes/automation.triggers'
import { Route as AutomationCallLogsRouteImport } from './routes/automation.call-logs'
import { Route as AutomationAgentsRouteImport } from './routes/automation.agents'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AutomationWorkflowsIndexRouteImport } from './routes/automation.workflows.index'
import { Route as AutomationWorkflowsWorkflowIdRouteImport } from './routes/automation.workflows.$workflowId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPipelinesRoute = SettingsPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFavoritesRoute = SettingsFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomFieldsRoute = SettingsCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrandingRoute = SettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsClientSlugRoute = ProjectsClientSlugRouteImport.update({
  id: '/projects/$clientSlug',
  path: '/projects/$clientSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsReputationRoute = InsightsReputationRouteImport.update({
  id: '/insights/reputation',
  path: '/insights/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsAnalyticsRoute = InsightsAnalyticsRouteImport.update({
  id: '/insights/analytics',
  path: '/insights/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxTemplatesRoute = InboxTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => InboxRoute,
} as any)
const InboxBroadcastsRoute = InboxBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => InboxRoute,
} as any)
const FinancialsReportsRoute = FinancialsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsPaymentsRoute = FinancialsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsInvoicesRoute = FinancialsInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinancialsRoute,
} as any)
const FinancialsEstimatesRoute = FinancialsEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => FinancialsRoute,
} as any)
const AutomationWorkflowsRoute = AutomationWorkflowsRouteImport.update({
  id: '/automation/workflows',
  path: '/automation/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationTriggersRoute = AutomationTriggersRouteImport.update({
  id: '/automation/triggers',
  path: '/automation/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationCallLogsRoute = AutomationCallLogsRouteImport.update({
  id: '/automation/call-logs',
  path: '/automation/call-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationAgentsRoute = AutomationAgentsRouteImport.update({
  id: '/automation/agents',
  path: '/automation/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationWorkflowsIndexRoute =
  AutomationWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AutomationWorkflowsRoute,
  } as any)
const AutomationWorkflowsWorkflowIdRoute =
  AutomationWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AutomationWorkflowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/files': typeof FilesRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automation/agents': typeof AutomationAgentsRoute
  '/automation/call-logs': typeof AutomationCallLogsRoute
  '/automation/triggers': typeof AutomationTriggersRoute
  '/automation/workflows': typeof AutomationWorkflowsRouteWithChildren
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/inbox/broadcasts': typeof InboxBroadcastsRoute
  '/inbox/templates': typeof InboxTemplatesRoute
  '/insights/analytics': typeof InsightsAnalyticsRoute
  '/insights/reputation': typeof InsightsReputationRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/custom-fields': typeof SettingsCustomFieldsRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/pipelines': typeof SettingsPipelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/projects/': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/files': typeof FilesRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automation/agents': typeof AutomationAgentsRoute
  '/automation/call-logs': typeof AutomationCallLogsRoute
  '/automation/triggers': typeof AutomationTriggersRoute
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/inbox/broadcasts': typeof InboxBroadcastsRoute
  '/inbox/templates': typeof InboxTemplatesRoute
  '/insights/analytics': typeof InsightsAnalyticsRoute
  '/insights/reputation': typeof InsightsReputationRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/custom-fields': typeof SettingsCustomFieldsRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/pipelines': typeof SettingsPipelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/projects': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows': typeof AutomationWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calendar': typeof CalendarRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/files': typeof FilesRoute
  '/financials': typeof FinancialsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/automation/agents': typeof AutomationAgentsRoute
  '/automation/call-logs': typeof AutomationCallLogsRoute
  '/automation/triggers': typeof AutomationTriggersRoute
  '/automation/workflows': typeof AutomationWorkflowsRouteWithChildren
  '/financials/estimates': typeof FinancialsEstimatesRoute
  '/financials/invoices': typeof FinancialsInvoicesRoute
  '/financials/payments': typeof FinancialsPaymentsRoute
  '/financials/reports': typeof FinancialsReportsRoute
  '/inbox/broadcasts': typeof InboxBroadcastsRoute
  '/inbox/templates': typeof InboxTemplatesRoute
  '/insights/analytics': typeof InsightsAnalyticsRoute
  '/insights/reputation': typeof InsightsReputationRoute
  '/projects/$clientSlug': typeof ProjectsClientSlugRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/custom-fields': typeof SettingsCustomFieldsRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/pipelines': typeof SettingsPipelinesRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/projects/': typeof ProjectsIndexRoute
  '/automation/workflows/$workflowId': typeof AutomationWorkflowsWorkflowIdRoute
  '/automation/workflows/': typeof AutomationWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/calendar'
    | '/companies'
    | '/contacts'
    | '/files'
    | '/financials'
    | '/forgot-password'
    | '/inbox'
    | '/leads'
    | '/marketing'
    | '/onboarding'
    | '/portal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/tasks'
    | '/auth/callback'
    | '/automation/agents'
    | '/automation/call-logs'
    | '/automation/triggers'
    | '/automation/workflows'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/inbox/broadcasts'
    | '/inbox/templates'
    | '/insights/analytics'
    | '/insights/reputation'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/branding'
    | '/settings/custom-fields'
    | '/settings/favorites'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/pipelines'
    | '/settings/team'
    | '/settings/templates'
    | '/projects/'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/calendar'
    | '/companies'
    | '/contacts'
    | '/files'
    | '/financials'
    | '/forgot-password'
    | '/inbox'
    | '/leads'
    | '/marketing'
    | '/onboarding'
    | '/portal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/tasks'
    | '/auth/callback'
    | '/automation/agents'
    | '/automation/call-logs'
    | '/automation/triggers'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/inbox/broadcasts'
    | '/inbox/templates'
    | '/insights/analytics'
    | '/insights/reputation'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/branding'
    | '/settings/custom-fields'
    | '/settings/favorites'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/pipelines'
    | '/settings/team'
    | '/settings/templates'
    | '/projects'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/calendar'
    | '/companies'
    | '/contacts'
    | '/files'
    | '/financials'
    | '/forgot-password'
    | '/inbox'
    | '/leads'
    | '/marketing'
    | '/onboarding'
    | '/portal'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/tasks'
    | '/auth/callback'
    | '/automation/agents'
    | '/automation/call-logs'
    | '/automation/triggers'
    | '/automation/workflows'
    | '/financials/estimates'
    | '/financials/invoices'
    | '/financials/payments'
    | '/financials/reports'
    | '/inbox/broadcasts'
    | '/inbox/templates'
    | '/insights/analytics'
    | '/insights/reputation'
    | '/projects/$clientSlug'
    | '/sales/pipeline'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/branding'
    | '/settings/custom-fields'
    | '/settings/favorites'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/permissions'
    | '/settings/pipelines'
    | '/settings/team'
    | '/settings/templates'
    | '/projects/'
    | '/automation/workflows/$workflowId'
    | '/automation/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CalendarRoute: typeof CalendarRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactsRoute: typeof ContactsRoute
  FilesRoute: typeof FilesRoute
  FinancialsRoute: typeof FinancialsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  MarketingRoute: typeof MarketingRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AutomationAgentsRoute: typeof AutomationAgentsRoute
  AutomationCallLogsRoute: typeof AutomationCallLogsRoute
  AutomationTriggersRoute: typeof AutomationTriggersRoute
  AutomationWorkflowsRoute: typeof AutomationWorkflowsRouteWithChildren
  InsightsAnalyticsRoute: typeof InsightsAnalyticsRoute
  InsightsReputationRoute: typeof InsightsReputationRoute
  ProjectsClientSlugRoute: typeof ProjectsClientSlugRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/pipelines': {
      id: '/settings/pipelines'
      path: '/pipelines'
      fullPath: '/settings/pipelines'
      preLoaderRoute: typeof SettingsPipelinesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/favorites': {
      id: '/settings/favorites'
      path: '/favorites'
      fullPath: '/settings/favorites'
      preLoaderRoute: typeof SettingsFavoritesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/custom-fields': {
      id: '/settings/custom-fields'
      path: '/custom-fields'
      fullPath: '/settings/custom-fields'
      preLoaderRoute: typeof SettingsCustomFieldsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branding': {
      id: '/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof SettingsBrandingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$clientSlug': {
      id: '/projects/$clientSlug'
      path: '/projects/$clientSlug'
      fullPath: '/projects/$clientSlug'
      preLoaderRoute: typeof ProjectsClientSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/reputation': {
      id: '/insights/reputation'
      path: '/insights/reputation'
      fullPath: '/insights/reputation'
      preLoaderRoute: typeof InsightsReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/analytics': {
      id: '/insights/analytics'
      path: '/insights/analytics'
      fullPath: '/insights/analytics'
      preLoaderRoute: typeof InsightsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/templates': {
      id: '/inbox/templates'
      path: '/templates'
      fullPath: '/inbox/templates'
      preLoaderRoute: typeof InboxTemplatesRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/broadcasts': {
      id: '/inbox/broadcasts'
      path: '/broadcasts'
      fullPath: '/inbox/broadcasts'
      preLoaderRoute: typeof InboxBroadcastsRouteImport
      parentRoute: typeof InboxRoute
    }
    '/financials/reports': {
      id: '/financials/reports'
      path: '/reports'
      fullPath: '/financials/reports'
      preLoaderRoute: typeof FinancialsReportsRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/payments': {
      id: '/financials/payments'
      path: '/payments'
      fullPath: '/financials/payments'
      preLoaderRoute: typeof FinancialsPaymentsRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/invoices': {
      id: '/financials/invoices'
      path: '/invoices'
      fullPath: '/financials/invoices'
      preLoaderRoute: typeof FinancialsInvoicesRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/financials/estimates': {
      id: '/financials/estimates'
      path: '/estimates'
      fullPath: '/financials/estimates'
      preLoaderRoute: typeof FinancialsEstimatesRouteImport
      parentRoute: typeof FinancialsRoute
    }
    '/automation/workflows': {
      id: '/automation/workflows'
      path: '/automation/workflows'
      fullPath: '/automation/workflows'
      preLoaderRoute: typeof AutomationWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/triggers': {
      id: '/automation/triggers'
      path: '/automation/triggers'
      fullPath: '/automation/triggers'
      preLoaderRoute: typeof AutomationTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/call-logs': {
      id: '/automation/call-logs'
      path: '/automation/call-logs'
      fullPath: '/automation/call-logs'
      preLoaderRoute: typeof AutomationCallLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/agents': {
      id: '/automation/agents'
      path: '/automation/agents'
      fullPath: '/automation/agents'
      preLoaderRoute: typeof AutomationAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/workflows/': {
      id: '/automation/workflows/'
      path: '/'
      fullPath: '/automation/workflows/'
      preLoaderRoute: typeof AutomationWorkflowsIndexRouteImport
      parentRoute: typeof AutomationWorkflowsRoute
    }
    '/automation/workflows/$workflowId': {
      id: '/automation/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/automation/workflows/$workflowId'
      preLoaderRoute: typeof AutomationWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AutomationWorkflowsRoute
    }
  }
}

interface FinancialsRouteChildren {
  FinancialsEstimatesRoute: typeof FinancialsEstimatesRoute
  FinancialsInvoicesRoute: typeof FinancialsInvoicesRoute
  FinancialsPaymentsRoute: typeof FinancialsPaymentsRoute
  FinancialsReportsRoute: typeof FinancialsReportsRoute
}

const FinancialsRouteChildren: FinancialsRouteChildren = {
  FinancialsEstimatesRoute: FinancialsEstimatesRoute,
  FinancialsInvoicesRoute: FinancialsInvoicesRoute,
  FinancialsPaymentsRoute: FinancialsPaymentsRoute,
  FinancialsReportsRoute: FinancialsReportsRoute,
}

const FinancialsRouteWithChildren = FinancialsRoute._addFileChildren(
  FinancialsRouteChildren,
)

interface InboxRouteChildren {
  InboxBroadcastsRoute: typeof InboxBroadcastsRoute
  InboxTemplatesRoute: typeof InboxTemplatesRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxBroadcastsRoute: InboxBroadcastsRoute,
  InboxTemplatesRoute: InboxTemplatesRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsBrandingRoute: typeof SettingsBrandingRoute
  SettingsCustomFieldsRoute: typeof SettingsCustomFieldsRoute
  SettingsFavoritesRoute: typeof SettingsFavoritesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsPipelinesRoute: typeof SettingsPipelinesRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsBrandingRoute: SettingsBrandingRoute,
  SettingsCustomFieldsRoute: SettingsCustomFieldsRoute,
  SettingsFavoritesRoute: SettingsFavoritesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsPipelinesRoute: SettingsPipelinesRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface AutomationWorkflowsRouteChildren {
  AutomationWorkflowsWorkflowIdRoute: typeof AutomationWorkflowsWorkflowIdRoute
  AutomationWorkflowsIndexRoute: typeof AutomationWorkflowsIndexRoute
}

const AutomationWorkflowsRouteChildren: AutomationWorkflowsRouteChildren = {
  AutomationWorkflowsWorkflowIdRoute: AutomationWorkflowsWorkflowIdRoute,
  AutomationWorkflowsIndexRoute: AutomationWorkflowsIndexRoute,
}

const AutomationWorkflowsRouteWithChildren =
  AutomationWorkflowsRoute._addFileChildren(AutomationWorkflowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CalendarRoute: CalendarRoute,
  CompaniesRoute: CompaniesRoute,
  ContactsRoute: ContactsRoute,
  FilesRoute: FilesRoute,
  FinancialsRoute: FinancialsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRouteWithChildren,
  LeadsRoute: LeadsRoute,
  MarketingRoute: MarketingRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AutomationAgentsRoute: AutomationAgentsRoute,
  AutomationCallLogsRoute: AutomationCallLogsRoute,
  AutomationTriggersRoute: AutomationTriggersRoute,
  AutomationWorkflowsRoute: AutomationWorkflowsRouteWithChildren,
  InsightsAnalyticsRoute: InsightsAnalyticsRoute,
  InsightsReputationRoute: InsightsReputationRoute,
  ProjectsClientSlugRoute: ProjectsClientSlugRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
